CREATE DATABASE IF NOT EXISTS demo;
USE demo;

-- DROP TABLE IF EXISTS t_user;
CREATE TABLE IF NOT EXISTS t_user (
  id       INT PRIMARY KEY AUTO_INCREMENT,
  name     VARCHAR(50)  UNIQUE NOT NULL,
  password VARCHAR(128) NOT NULL
);